
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-01-16T13:01:01-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "273160443373dc0b68f68a2a64e12b93057618f9",
 "version": "5.0.0a12"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
